name: Continuous Integration
on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
env:
  GRADLE_OPTS: >-
    -Dorg.gradle.project.sonatypeUsername=${{ secrets.SONATYPE_S01_USERNAME }}
    -Dorg.gradle.project.sonatypePassword=${{ secrets.SONATYPE_S01_PASSWORD }}
    -Dorg.gradle.project.signingKeyId=CDE3528F
    -Dorg.gradle.project.signingKey=${{ secrets.MAVEN_CENTRAL_GPG_KEY }}
    -Dorg.gradle.project.signingPassword=${{ secrets.MAVEN_CENTRAL_GPG_PASSWORD }}
jobs:
  buildAndPublish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build Amp
        run: ./gradlew amp --info
      - name: Publish Amp
        if: ${{ startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/head/master') }}
        run: ./gradlew publish --info
