name: Continuous Integration
on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
env:
  ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_S01_USERNAME }}
  ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_S01_PASSWORD }}
  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.MAVEN_CENTRAL_GPG_KEY }}
  ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.MAVEN_CENTRAL_GPG_PASSWORD }}
jobs:
  buildAndPublish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build Amp
        run: ./gradlew amp --info
      - name: Publish Amp
        if: ${{ startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/heads/master') }}
        run: ./gradlew publish --info
